"""Load the browser's frequency word lists so the server ranks vocabulary
identically to the local engine.

The lists live as JS modules (`export default "word1 word2 ...";`) generated by
scripts/build-freq.mjs. We extract the single JSON string literal from each.
Rank = index in the list (0 = most frequent).
"""
import json
from functools import lru_cache

from .config import FREQ_DATA_DIR


def _extract_word_string(js_source: str) -> str:
    # Everything after the last `export default ` is a JSON string ending in `;`.
    marker = "export default "
    idx = js_source.rfind(marker)
    if idx == -1:
        return ""
    rest = js_source[idx + len(marker):].strip()
    if rest.endswith(";"):
        rest = rest[:-1].strip()
    try:
        return json.loads(rest)
    except json.JSONDecodeError:
        return ""


@lru_cache(maxsize=None)
def rank_map(lang: str) -> dict:
    """word -> rank index (lower = more frequent). Empty dict if list missing."""
    path = FREQ_DATA_DIR / f"freq-{lang}.js"
    try:
        source = path.read_text(encoding="utf-8")
    except OSError:
        return {}
    words = _extract_word_string(source).split(" ")
    return {w: i for i, w in enumerate(words) if w}


def band_from_rank(rank) -> int:
    """Map a frequency rank to a difficulty band 1 (A1) … 6 (C2).

    Mirrors the thresholds in src/cefr.js so both engines agree on vocabulary
    difficulty.
    """
    if rank is None:
        return 6
    if rank < 500:
        return 1
    if rank < 1000:
        return 2
    if rank < 2000:
        return 3
    if rank < 3500:
        return 4
    if rank < 6000:
        return 5
    return 6
