// One-time generator: builds src/grammar/data/de-gender.js — a compact German
// noun→gender lookup for the LOCAL (heuristic) grammar analyzer. German gender
// is lexical, so the offline analyzer needs a table; the server path (spaCy) is
// exact and doesn't use this.
//
// Source: gambolputty/german-nouns (MIT) — a Wiktionary-derived CSV of ~100k
// German nouns with their grammatical gender ("genus"). We intersect it with the
// existing frequency list (src/data/freq-de.js, OpenSubtitles top-N) so the
// shipped table stays small: only reasonably common nouns are kept.
//
//   Run: node scripts/build-lexicon.mjs
//
// License note: german-nouns is MIT; the underlying data derives from the German
// Wiktionary (CC BY-SA). Keep this attribution if the generated file is shipped.
import { writeFileSync } from 'fs';

import freqDe from '../src/data/freq-de.js';

const CSV_URL =
  'https://raw.githubusercontent.com/gambolputty/german-nouns/main/german_nouns/nouns.csv';

// genus code (Wiktionary) → UD-style Gender value used across the grammar contract.
const GENUS = { m: 'Masc', f: 'Fem', n: 'Neut' };

// Frequency vocabulary (lowercased) → keep only nouns whose lemma appears here.
const freqSet = new Set(freqDe.split(' '));

// Minimal CSV splitter that respects double-quoted fields (german-nouns quotes
// values containing commas). Sufficient for this well-formed dataset.
function splitCsvLine(line) {
  const out = [];
  let field = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (inQuotes) {
      if (c === '"' && line[i + 1] === '"') { field += '"'; i++; }
      else if (c === '"') inQuotes = false;
      else field += c;
    } else if (c === '"') {
      inQuotes = true;
    } else if (c === ',') {
      out.push(field); field = '';
    } else {
      field += c;
    }
  }
  out.push(field);
  return out;
}

const raw = await fetch(CSV_URL).then((r) => {
  if (!r.ok) throw new Error(`fetch failed: ${r.status} ${r.statusText}`);
  return r.text();
});

const lines = raw.split('\n');
const header = splitCsvLine(lines[0]).map((h) => h.trim().toLowerCase());
const lemmaCol = header.indexOf('lemma');
// Primary gender column ("genus"); some rows carry genus 1/2/3 for ambiguous nouns.
const genusCol = header.indexOf('genus') !== -1 ? header.indexOf('genus') : header.indexOf('genus 1');
if (lemmaCol === -1 || genusCol === -1) {
  throw new Error(`unexpected CSV header: ${header.join(', ')}`);
}

const table = {};
for (let i = 1; i < lines.length; i++) {
  const line = lines[i];
  if (!line) continue;
  const cols = splitCsvLine(line);
  const lemma = cols[lemmaCol]?.trim();
  const genus = cols[genusCol]?.trim().toLowerCase();
  if (!lemma || !GENUS[genus]) continue;               // skip missing/ambiguous gender
  if (/\s/.test(lemma)) continue;                       // single tokens only
  if (!freqSet.has(lemma.toLowerCase())) continue;      // keep it compact
  if (table[lemma]) continue;                           // first (primary) gender wins
  table[lemma] = GENUS[genus];
}

const entries = Object.keys(table).sort((a, b) => a.localeCompare(b, 'de'));
const body = entries.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(table[k])},`).join('\n');

const out = new URL('../src/grammar/data/de-gender.js', import.meta.url);
writeFileSync(
  out,
  `// Auto-generated by scripts/build-lexicon.mjs — ${entries.length} common German\n` +
  `// nouns → gender (Masc/Fem/Neut), intersected with the top OpenSubtitles words.\n` +
  `// Source: gambolputty/german-nouns (MIT; data from German Wiktionary, CC BY-SA).\n` +
  `//\n` +
  `// German gender is lexical, so the local heuristic analyzer needs this lookup.\n` +
  `// Coverage is partial by design — unknown nouns get no gender locally (the\n` +
  `// server/spaCy path is exact). Keys are the noun as normally written.\n` +
  `export default {\n${body}\n};\n`
);
console.log(`de-gender.js: ${entries.length} nouns`);
