// One-time generator: fetches OpenSubtitles word-frequency lists (hermitdave/
// FrequencyWords, MIT) for PT and DE and writes compact frequency modules.
// Rank = array index (0 = most frequent). Run: node scripts/build-freq.mjs
import { writeFileSync, mkdirSync } from 'fs';

const TOP_N = 6000;
const SOURCES = {
  de: 'https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/de/de_50k.txt',
  pt: 'https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/pt/pt_50k.txt',
};

// Keep only real words (letters incl. accents, ß, hyphen/apostrophe inside).
const WORD_RE = /^[\p{L}][\p{L}''-]*$/u;

mkdirSync(new URL('../src/data/', import.meta.url), { recursive: true });

for (const [lang, url] of Object.entries(SOURCES)) {
  const raw = await fetch(url).then(r => r.text());
  const words = [];
  for (const line of raw.split('\n')) {
    const word = line.split(' ')[0]?.trim().toLowerCase();
    if (word && WORD_RE.test(word)) words.push(word);
    if (words.length >= TOP_N) break;
  }
  const out = new URL(`../src/data/freq-${lang}.js`, import.meta.url);
  writeFileSync(
    out,
    `// Auto-generated by scripts/build-freq.mjs — top ${words.length} ${lang.toUpperCase()} words\n` +
    `// by frequency (OpenSubtitles 2018, hermitdave/FrequencyWords, MIT). Rank = index.\n` +
    `export default ${JSON.stringify(words.join(' '))};\n`
  );
  console.log(`freq-${lang}.js: ${words.length} words`);
}
